# Generated by Django 5.1.5 on 2025-02-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_blogpagetags_detailpage_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.customimage",
            ),
        ),
    ]
