# Generated by Django 5.1.6 on 2025-02-15 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_streampage"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cta_primary_text",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_primary_url",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_sub_title",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
