# Generated by Django 5.1.6 on 2025-02-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_homepage_cta_primary_text_homepage_cta_primary_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="cta_sub_title",
            new_name="cta_subtitle",
        ),
    ]
